version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build and push docker image
          command: |
            APP=${CIRCLE_PROJECT_REPONAME}
            TAG=${CIRCLE_SHA1:0:7}
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} quay.io
            docker build -t quay.io/collectai/${APP}:${TAG} .
            docker push quay.io/collectai/${APP}:${TAG}
            docker tag quay.io/collectai/${APP}:${TAG} quay.io/collectai/${APP}:latest
            docker push quay.io/collectai/${APP}:latest
